### ISSUE TITLE
bug: preprocess index 与编辑按钮的矛盾

### ISSUE THREAD

**Issue by chinanf-boy** [chinanf-boy/mdbook-nice-example#1]
- book.toml

``` toml
preprocess = ["links", "index"]
# 默认情况
```

> [mdbook中文文档](http://llever.com/mdBook-zh/format/config.zh.html?highlight=index#build-%E9%80%89%E9%A1%B9)

- src目录结构

```
- src
	- 01
		- README.md/readme.md(不管大小写)
	- other
```

book.toml的`index`会把*01/REAMDE.md*变成网页的**01/index.html**

- 编辑按钮

是按照网址路径，另开github项目的编辑网址

```
https://github.com/chinanf-boy/mdbook-nice-example/edit/master/src/01/index.md
```

**很明显，我们只有REAMDE.md没有index.md,所以编辑出错了**

而 网址是区分大小写的，被mdBook生成的静态页面目录中，已经不存在原始目录（readme.md => index.md）

## 解决(不能兼顾)

- **1.** 不使用 preprocess的"index" 我决定这个✅
- **2.** 不使用 readme/README.md作为文章名，使用index.md

**Comment by chinanf-boy** [comment]
## book.toml

``` toml
[build]
build-dir = "docs"
create-missing = true
use-default-preprocessors = false
preprocess = ["links"]
```
